#!/bin/bash

EXE=$1
ARGS="-b 4"

# TODO: Get list of target/mode pairs from --list

# Test each mode without bitflips
for mode in none constraints sed sec7 sec8 secded
do
  $EXE $ARGS -m $mode >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $EXE $mode"
  else
    echo "FAILED $EXE $mode"
  fi
done

# Test modes with single-bit error detection with a single bit-flip
for mode in sed
do
  $EXE $ARGS -m $mode -x | grep 'error detected at index' >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $EXE $mode -x"
  else
    echo "FAILED $EXE $mode -x"
  fi
done

# Test modes with correction capabilities with a single bit-flip
for mode in sec7 sec8 secded
do
  $EXE $ARGS -m $mode -x >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $EXE $mode -x"
  else
    echo "FAILED $EXE $mode -x"
  fi
done

# Test modes with double-bit error detection with a double bit-flip
for mode in secded
do
  $EXE $ARGS -m $mode -x 2 | grep 'double-bit error detected' >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $EXE $mode -x 2"
  else
    echo "FAILED $EXE $mode -x 2"
  fi
done
