#!/bin/bash

EXE=$1
ARGS="-b 4"

# Get list of target/mode pairs
IMPLEMENTATIONS=$($EXE --list | grep '-')

# Test each mode without bitflips
for IMPL in $IMPLEMENTATIONS
do
  target=$(echo $IMPL | awk -F '-' '{print $1}')
  mode=$(echo $IMPL | awk -F '-' '{print $2}')
  cmd="$EXE $ARGS -t $target -m $mode"
  $cmd >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $cmd"
  else
    echo "FAILED $cmd"
  fi
done

# Test modes with single-bit error detection with a single bit-flip
for IMPL in $IMPLEMENTATIONS
do
  if [ "$(echo $IMPL | grep sed)" == "" ]
  then
    continue;
  fi

  target=$(echo $IMPL | awk -F '-' '{print $1}')
  mode=$(echo $IMPL | awk -F '-' '{print $2}')
  cmd="$EXE $ARGS -t $target -m $mode -x"
  $cmd | grep 'error detected at index' >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $cmd"
  else
    echo "FAILED $cmd"
  fi
done

# Test modes with correction capabilities with a single bit-flip
for IMPL in $IMPLEMENTATIONS
do
  if [ "$(echo $IMPL | grep sec)" == "" ]
  then
    continue;
  fi

  target=$(echo $IMPL | awk -F '-' '{print $1}')
  mode=$(echo $IMPL | awk -F '-' '{print $2}')
  cmd="$EXE $ARGS -t $target -m $mode -x"
  $cmd >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $cmd"
  else
    echo "FAILED $cmd"
  fi
done

# Test modes with double-bit error detection with a double bit-flip
for IMPL in $IMPLEMENTATIONS
do
  if [ "$(echo $IMPL | grep secded)" == "" ]
  then
    continue;
  fi

  target=$(echo $IMPL | awk -F '-' '{print $1}')
  mode=$(echo $IMPL | awk -F '-' '{print $2}')
  cmd="$EXE $ARGS -t $target -m $mode -x 2"
  $cmd | grep 'double-bit error detected' >/dev/null
  if [ $? -eq 0 ]
  then
    echo "passed $cmd"
  else
    echo "FAILED $cmd"
  fi
done
